name: Health check

on:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  health_check_application:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://blogapp-ubxl.onrender.com
          max-attempts: 3 
          retry-delay: 5s